.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SIL-CONVERTERS SECTION "January 30, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sil-converters \- programs for converting text encodings
.SH SYNOPSIS
.B ClipboardEC.exe
.br
.B DChartHelper.exe
.br
.B SFMConv.exe
.br
.B SilConvertersXML.exe
.SH DESCRIPTION
This manual page documents briefly the
.B sil-converters
package of programs.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBsil-converters\fP is a set of programs that use the
\fBenc-converters\fP libraries in useful ways.
.SH SEE ALSO
.BR enc-converters (3).
.br
I'm sure there's documentation on all this stuff somewhere.
.SH AUTHOR
The sil-converters programs were written by Bob Eaton.
.PP
This manual page was written by Stephen McConnel <stephen_mcconnel@sil.org>,
as a stopgap measure (and may be used by others).
