# Build silconverters and run tests

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "./SEC VS2019.sln"

jobs:
  build-windows:
    runs-on: [windows-latest]

    strategy:
      # Keep building other jobs even if another fails, to show what is still working.
      fail-fast: false
      matrix:
        build_configuration: ["Debug", "Release"]
        build_platform: ['x64', 'x86']

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # fetch full history for GitVersion

      # ✅ Install ATL/MFC support
      - name: Install missing Visual Studio ATL components
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $vsInstallPath = & .\vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          $atlComponent = @(
          '--add Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64',
          '--add Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL',
          '--add Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC'
          ) -join ' '
          $args = @('modify', "--installPath", "`"$vsInstallPath`"", $atlComponent, '--quiet', '--norestart', '--nocache')
          Start-Process -FilePath .\vs_installer.exe -ArgumentList $args -Wait -PassThru -WindowStyle Hidden

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Fetch NuGet dependencies
        run: nuget restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.build_platform }}

      - name: Build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild /m /p:Configuration=${{ matrix.build_configuration }} /p:Platform=${{ matrix.build_platform }} "${{ env.SOLUTION_FILE_PATH }}"
